pin setuptools to v30.4.0
 * Running invoke install -d with setuptools v31 can break
   waterbutler.  The symptom error message is: "AttributeError: module
   'waterbutler' has no attribute '__version__'".  If you encounter
   this, you will need to remove the file
   lib/python3.5/site-packages/waterbutler-nspkg.pth from your
   virtualenv directory, run `pip install setuptools==30.4.0`, then
   re-run `invoke install -d`.