tests: dataverse updates
 * fix test_metadata_never_published -
   waterbutler.core.exceptions.MetadataError: 404, None , for now
   'latest-published' produce error TODO: maybe that fix is needed to
   be updated somehow

 * fix Exception: No URLs matching GET
   https://myfakehost.dataverse.org/api/v1/datasets/18/versions/%253Alatest?key=wrote+harry+potter
   with params {'key': 'wrote harry potter'}. Not making request. Go
   fix your test.

 * TODO: suggestion related to
   'test_metadata_never_published_raises_errors' logic