update s3 providers and tests for boto3
 * initial commit (many testing code) - trying to find out why there
   may be problems with signature on some requests (for example
   _complete_multipart_upload)

 * found work around for '_complete_multipart_upload' with config =
   AioConfig(signature_version='s3v4'), trying to find for others
   requests, for example for '_abort_chunked_upload' got for now
   2025-05-15T13:21:20.637311375Z
   waterbutler.core.exceptions.UploadError: 403, {"response": "<?xml
   version=\"1.0\"
   encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The
   request signature we calculated does not match the signature you
   provided. Check your key and signing method ...c 4f 41
   44</CanonicalRequestBytes><RequestId>42Q4F2F8SDWMFVHX</RequestId><HostId>osG5j/y2tPRMoIelFMON/qSvV+oPZk7EvwcVAMdTlbCnckHJ66LRAInG5vg6dCne7wrmZtJsRdBMyi0yN1w1Bux+zoQ7MEWG</HostId></Error>"}

 * s3 provider code updates for 'presigned_url' usage (need to
   refactor it to be it more clear )

 * Checking folder s3 existence with 'presigned_url' 'list_objects_v2'
   call

 * refactor code s3 code and generate_presigned_url for location

 * use 'get_folder_metadata' in pair with
   'generate_generic_presigned_url'

 * code updates with research and suggestion #todo

 * add xml characters decoding to file name that was uploaded by user
   previously for 'get_folder_metadata'

 * add possible changings for 'get_object_versions' (not confident how
   to test it out from UI(front-end side)), add additional casting for
   folders removal

 * check and rewrite unit testing where it is needed